/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Internal,
  IERC20InternalInterface,
} from "../../../../../../lib/morpho-blue/src/libraries/SafeTransferLib.sol/IERC20Internal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Internal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20InternalInterface {
    return new Interface(_abi) as IERC20InternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20Internal {
    return new Contract(address, _abi, runner) as unknown as IERC20Internal;
  }
}
