/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMorphoFlashLoanCallback,
  IMorphoFlashLoanCallbackInterface,
} from "../../../../../../lib/morpho-blue/src/interfaces/IMorphoCallbacks.sol/IMorphoFlashLoanCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onMorphoFlashLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMorphoFlashLoanCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IMorphoFlashLoanCallbackInterface {
    return new Interface(_abi) as IMorphoFlashLoanCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMorphoFlashLoanCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMorphoFlashLoanCallback;
  }
}
