/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMorphoRepayCallback,
  IMorphoRepayCallbackInterface,
} from "../../../../../../lib/morpho-blue/src/interfaces/IMorphoCallbacks.sol/IMorphoRepayCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onMorphoRepay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMorphoRepayCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IMorphoRepayCallbackInterface {
    return new Interface(_abi) as IMorphoRepayCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMorphoRepayCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMorphoRepayCallback;
  }
}
