/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMorphoSupplyCollateralCallback,
  IMorphoSupplyCollateralCallbackInterface,
} from "../../../../../../lib/morpho-blue/src/interfaces/IMorphoCallbacks.sol/IMorphoSupplyCollateralCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onMorphoSupplyCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMorphoSupplyCollateralCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IMorphoSupplyCollateralCallbackInterface {
    return new Interface(_abi) as IMorphoSupplyCollateralCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMorphoSupplyCollateralCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMorphoSupplyCollateralCallback;
  }
}
