/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMorpho } from "./IMorpho";
export type { IMorphoBase } from "./IMorphoBase";
export type { IMorphoStaticTyping } from "./IMorphoStaticTyping";
