/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IUniversalRewardsDistributor__factory } from "./IUniversalRewardsDistributor__factory";
export { IUniversalRewardsDistributorBase__factory } from "./IUniversalRewardsDistributorBase__factory";
export { IUniversalRewardsDistributorStaticTyping__factory } from "./IUniversalRewardsDistributorStaticTyping__factory";
